"""Add content and quiz models

Revision ID: 545b36fd4489
Revises: 3f55212e8b92
Create Date: 2024-05-27 14:50:27.689293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545b36fd4489'
down_revision = '3f55212e8b92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=200), nullable=False),
    sa.Column('answer', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz')
    op.drop_table('content')
    # ### end Alembic commands ###
