"""Alter models

Revision ID: a6672bad8846
Revises: c18bcb48f636
Create Date: 2024-06-01 10:34:16.271749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6672bad8846'
down_revision = 'c18bcb48f636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('choices', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('correct_answer', sa.String(length=200), nullable=False))
        batch_op.drop_column('answer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('correct_answer')
        batch_op.drop_column('choices')

    # ### end Alembic commands ###
